export default  {

 pmrozgarmelapic : '../../assets/images/pm-rozgar-mela.png',
 PolLogo : '../../assets/images/logo/policy-logo.png',
 byjusLogo : '../../assets/images/logo/byjus-logo.png',
 itchotelLogo : '../../assets/images/logo/itchotel-logo.png',
 adityabLogo : '../../assets/images/logo/adityab-logo.png',
 classplusLogo : '../../assets/images/logo/classPlus-logo.png',
 gistechLogo : '../../assets/images/logo/gistech-logo.png',
 zindgitechLogo : '../../assets/images/logo/zindgitech-logo.png',
 lendenctech : '../../assets/images/logo/lendenctech-logo.png',
 jobalerticon : '../../assets/images/job-alert-icons.jpg',
 freecreatecv : '../../assets/images/free-create-cv.jpg',
 pmrozgarMela : '../../assets/images/pm-rozgar-mela-icon.png',
//  { getPremiumJobs, getPrmiumJobsandfe, getSaveJobList, SaveJobs } : '@/action/CandidateAction',
  Companylogo : '../../assets/images/COMPANY_LOGO.png',
 moment : 'moment',
 JobPopular  : '../../assets/images/jop-popular.jpg' ,
 AccYourJobSearch  : '../../assets/images/acc-your-job-search.jpg', 
 NextInterView    : '../../assets/images/next-interview.png',
 JavaLogo  : '../../assets/images/java-logo.jpg',
  PythonLogo  : '../../assets/images/python-logo.jpg',
 PHPLogo   : '../../assets/images/php-logo.jpg',
  CognizantLogo : '../../assets/images/cognizant-logo.jpg' ,
  AccLogo  : '../../assets/images/acc-logo.jpg', 
 byjuLogo : '../../assets/images/byju-logo.jpg',
  TcsLogo : '../../assets/images/tcs-logo.jpg',
 AndroidImg  : '../../assets/images/android-img.png',
  AppleImg  : '../../assets/images/apple-img.png',
  Appdev  : '../../assets/images/appdev.png',
  AppShapeRight  : '../../assets/images/app-shape-right.png' ,


     
}